### ISSUE TITLE
Random `undefined` cards popping up ingame

### ISSUE THREAD

**Issue by JMTNTBANG** [JMTNTBANG/The-Card-Game-Bot#2]
its adding `undefined` to the hand at random times, which causes the bot to crash

Exception:
```js
/home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:6
  if (card.type == "number" && card.color != "wild") {
           ^

TypeError: Cannot read properties of undefined (reading 'type')
    at print_card (/home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:6:12)
    at /home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:63:25
    at Array.forEach (<anonymous>)
    at /home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:62:19
    at Array.forEach (<anonymous>)
    at show_hands (/home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:60:6)
    at sent_thread_cmd (/home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:202:9)
    at MessageCollector.<anonymous> (/home/ubuntu/Bots/The-Card-Game-Bot/src/games/uno.js:256:31)
    at MessageCollector.emit (node:events:519:28)
    at MessageCollector.handleCollect (/home/ubuntu/Bots/The-Card-Game-Bot/node_modules/discord.js/src/structures/interfaces/Collector.js:133:14)
```
User Feed:
![image](https://github.com/JMTNTBANG/The-Card-Game-Bot/assets/32822936/aacf4027-2109-40b1-b9ab-f0fb3a644135)

Channel URL:
https://discord.com/channels/1074900282133184542/1208278151843545098

**Comment by JMTNTBANG** [comment]
So this wasnt just a deck rollover issue, its still happening
